-- SQL Server schema for Restaurant Management System

CREATE TABLE users (
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  name NVARCHAR(255) NOT NULL,
  username NVARCHAR(64) NOT NULL UNIQUE,
  email NVARCHAR(255) NOT NULL UNIQUE,
  password_hash NVARCHAR(255) NOT NULL,
  role NVARCHAR(20) NOT NULL,
  is_active BIT NOT NULL DEFAULT 1,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE tables (
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  number INT NOT NULL UNIQUE,
  name NVARCHAR(255) NULL,
  seating_capacity INT NOT NULL,
  assigned_waiter_id UNIQUEIDENTIFIER NULL,
  status NVARCHAR(30) NOT NULL DEFAULT 'FREE',
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

-- (Other tables analogous to PostgreSQL schema)

